/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlCategoriaProductos;
import Controlador.CtlCuentaPersonal;
import Controlador.CtlHabitacion;
import Controlador.CtlHistorialCuentaPersonal;
import Controlador.CtlInventarioProductos;
import Controlador.CtlReserva;
import Excepcion.BuscarCategoriaException;
import Excepcion.BuscarCuentaPersonalException;
import Excepcion.BuscarInventarioException;
import Excepcion.CantidadProductoException;
import Excepcion.CargarImagenException;
import Excepcion.DatosIncompletosException;
import Excepcion.GuardarHistorialCuentaPersonalException;
import Excepcion.ModificarCantidadException;
import Excepcion.ModificarInventarioException;
import Excepcion.NombreProductoException;
import Modelo.CategoriaProducto;
import Modelo.CuentaPersonal;
import Modelo.Habitacion;
import Modelo.Huesped;
import Modelo.Producto;
import Modelo.Recepcionista;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class FrmProductos extends javax.swing.JFrame {

    private final CtlHistorialCuentaPersonal controlador;
    private final CtlInventarioProductos controladorproductos;
    private final CtlCategoriaProductos controladorcategoria;
    private final CtlCuentaPersonal controladorCuentaPersonal;
    private Huesped huesped;

    public FrmProductos() {
        initComponents();
        controlador = new CtlHistorialCuentaPersonal();
        controladorproductos = new CtlInventarioProductos();
        controladorcategoria = new CtlCategoriaProductos();
        controladorCuentaPersonal = new CtlCuentaPersonal();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cbxCategoria.setEnabled(false);
        cbxProductos.setEnabled(false);
        btnSolicitar.setEnabled(false);
    }

    public FrmProductos(Huesped huesped) {
        initComponents();
        this.huesped = huesped;
        controlador = new CtlHistorialCuentaPersonal();
        controladorproductos = new CtlInventarioProductos();
        controladorcategoria = new CtlCategoriaProductos();
        controladorCuentaPersonal = new CtlCuentaPersonal();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        llenarComboBoxCategoria();
        llenarComboBoxReservacion();
        cbxCategoria.setEnabled(false);
        cbxProductos.setEnabled(false);
        btnSolicitar.setEnabled(false);
        cargarInfo(huesped);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnSolicitar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblNombreProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescripcion = new javax.swing.JTextArea();
        lblValorUnitario = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblValornoche1 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        lblSeleccione1 = new javax.swing.JLabel();
        cbxProductos = new javax.swing.JComboBox<>();
        lblSeleccione2 = new javax.swing.JLabel();
        lblSeleccione3 = new javax.swing.JLabel();
        cbxReserva = new javax.swing.JComboBox<>();
        btnSolicitar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblCedula.setBackground(new java.awt.Color(255, 255, 255));
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("CEDULA");

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logousuarios.png"))); // NOI18N

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("NOMBRE COMPLETO");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblCedula)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        btnSolicitar.setBackground(new java.awt.Color(255, 255, 255));
        btnSolicitar.setForeground(new java.awt.Color(102, 0, 0));
        btnSolicitar.setText("SOLICITAR");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen.setMaximumSize(new java.awt.Dimension(4, 4));
        lblImagen.setMinimumSize(new java.awt.Dimension(4, 4));

        cbxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cbxCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cbxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxCategoriaMouseClicked(evt);
            }
        });
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });

        lblNombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreProducto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreProducto.setText("NOMBRE PRODUCTO");

        lblDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setColumns(20);
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setRows(5);
        jScrollPane1.setViewportView(lblDescripcion);

        lblValorUnitario.setBackground(new java.awt.Color(255, 255, 255));
        lblValorUnitario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblValorUnitario.setForeground(new java.awt.Color(0, 0, 0));
        lblValorUnitario.setText("VALOR INDIVIDUAL");

        lblValor.setBackground(new java.awt.Color(255, 255, 255));
        lblValor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(0, 0, 0));
        lblValor.setText("VALOR");
        lblValor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("PRODUCTOS DISPONIBLES");

        lblValornoche1.setBackground(new java.awt.Color(255, 255, 255));
        lblValornoche1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblValornoche1.setForeground(new java.awt.Color(0, 0, 0));
        lblValornoche1.setText("CANTIDAD :");

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblSeleccione1.setBackground(new java.awt.Color(255, 255, 255));
        lblSeleccione1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSeleccione1.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccione1.setText("Seleccione Producto:");

        cbxProductos.setBackground(new java.awt.Color(255, 255, 255));
        cbxProductos.setForeground(new java.awt.Color(0, 0, 0));
        cbxProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxProductosMouseClicked(evt);
            }
        });
        cbxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductosActionPerformed(evt);
            }
        });

        lblSeleccione2.setBackground(new java.awt.Color(255, 255, 255));
        lblSeleccione2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSeleccione2.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccione2.setText("Seleccione Reserva  :");

        lblSeleccione3.setBackground(new java.awt.Color(255, 255, 255));
        lblSeleccione3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSeleccione3.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccione3.setText("Seleccione Categoria:");

        cbxReserva.setBackground(new java.awt.Color(255, 255, 255));
        cbxReserva.setForeground(new java.awt.Color(0, 0, 0));
        cbxReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxReservaMouseClicked(evt);
            }
        });
        cbxReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxReservaActionPerformed(evt);
            }
        });

        btnSolicitar1.setBackground(new java.awt.Color(255, 255, 255));
        btnSolicitar1.setForeground(new java.awt.Color(102, 0, 0));
        btnSolicitar1.setText("CANCELAR");
        btnSolicitar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSeleccione3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblSeleccione1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreProducto)
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(54, 54, 54)
                                                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(lblValornoche1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(spnCantidad))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(lblValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                                .addContainerGap())
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblSeleccione2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnSolicitar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(214, 214, 214))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSeleccione2)
                        .addComponent(cbxReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSolicitar1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto)
                    .addComponent(lblSeleccione1)
                    .addComponent(lblSeleccione3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblValorUnitario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblValor)
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblValornoche1)
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmMenuHuesped menu = new FrmMenuHuesped(huesped);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        try {
            int idReserva = Integer.parseInt(cbxReserva.getSelectedItem().toString());
            CuentaPersonal cuenta = controladorCuentaPersonal.buscarCuentaPersonal(idReserva);
            int idCuentaPersonal = cuenta.getId();
            String nombreproducto = cbxProductos.getSelectedItem().toString();
            Producto producto = controladorproductos.buscarInventario(nombreproducto);
            String cantidad = spnCantidad.getValue().toString();
            controlador.guardarHistorialCuentaPersonal(idCuentaPersonal, producto.getId(), cantidad);
            JOptionPane.showMessageDialog(null, "Se Solicito el Producto Correcto");
        } catch (DatosIncompletosException | BuscarInventarioException | GuardarHistorialCuentaPersonalException | ModificarInventarioException | NombreProductoException | ModificarCantidadException | BuscarCuentaPersonalException | CantidadProductoException e) {
            imprimir(e.getMessage());
        }
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void cbxCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaMouseClicked
        try {
            String nombre = cbxCategoria.getSelectedItem().toString();
            CategoriaProducto categoria = controladorcategoria.buscarCategoriaProductos(nombre);
            int idcategoria = categoria.getId();

            cbxProductos.setModel(controlador.llenarComboBoxProductos(idcategoria));

        } catch (DatosIncompletosException | BuscarCategoriaException e) {
            imprimir(e.getMessage());
        }
    }//GEN-LAST:event_cbxCategoriaMouseClicked

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void cbxProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxProductosMouseClicked
        String nombre = cbxProductos.getSelectedItem().toString();

        try {
            Producto producto = controladorproductos.buscarInventario(nombre);
            lblNombreProducto.setText(producto.getNombre());
            lblValor.setText(producto.getPrecioUnitario());
            lblDescripcion.setText(producto.getDescripcion());
            lblImagen.setIcon(new ImageIcon(controladorproductos.cargarImagenBufferedImage(producto.getImagen())));
        } catch (DatosIncompletosException | BuscarInventarioException | CargarImagenException e) {
            imprimir(e.getMessage());
        }
    }//GEN-LAST:event_cbxProductosMouseClicked

    private void cbxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProductosActionPerformed

    private void cbxReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxReservaMouseClicked
        if (cbxReserva.getItemCount() != 0) {
            cbxCategoria.setEnabled(true);
            cbxProductos.setEnabled(true);
            btnSolicitar.setEnabled(true);
        }
    }//GEN-LAST:event_cbxReservaMouseClicked

    private void cbxReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxReservaActionPerformed

    private void btnSolicitar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitar1ActionPerformed
        limpiar();
    }//GEN-LAST:event_btnSolicitar1ActionPerformed
    private void cargarInfo(Huesped x) {
        lblCedula.setText(x.getCedula());
        lblNombre.setText(x.getNombrecompleto());

    }

    private void limpiar() {
        cbxCategoria.setSelectedItem("");
        cbxCategoria.setEnabled(false);
        cbxProductos.setSelectedItem("");
        cbxProductos.setEnabled(false);
        btnSolicitar.setEnabled(false);
        lblNombreProducto.setText("NOMBRE PRODUCTO");
        lblValor.setText("VALOR");
        spnCantidad.setValue(0);
        lblDescripcion.setText("");
        lblImagen.setIcon(null);
    }

    private void llenarComboBoxReservacion() {
        cbxReserva.setModel(controlador.llenarComboBoxReserva(huesped.getId()));
    }

    private void llenarComboBoxCategoria() {
        cbxCategoria.setModel(controlador.llenarComboBoxCategoria());
    }

    private void imprimir(String v) {
        JOptionPane.showMessageDialog(null, v);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton btnSolicitar1;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxHabitacion;
    private javax.swing.JComboBox<String> cbxHabitacion1;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JComboBox<String> cbxReserva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JTextArea lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblSeleccione1;
    private javax.swing.JLabel lblSeleccione2;
    private javax.swing.JLabel lblSeleccione3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorUnitario;
    private javax.swing.JLabel lblValornoche1;
    private javax.swing.JSpinner spnCantidad;
    // End of variables declaration//GEN-END:variables
}
